### ISSUE TITLE
SDNEXT: Error only on server restart:  "ValueError: zip() argument 2 is longer than argument 1"

### ISSUE THREAD

**Issue by RGX650** [John-WL/sd-webui-inpaint-difference#10]
15:10:55-506926 INFO     Hacking i2i-batch is already done.
╭────────────────────────── Traceback (most recent call last) ───────────────────────────╮
│ C:\AI\SDNEXT\automatic\launch.py:246 in <module>                                       │
│                                                                                        │
│   245                 installer.log.info('Server restarting...')                       │
│ ❱ 246                 uv, instance = start_server(immediate=False, server=instance)    │
│   247             else:                                                                │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\launch.py:171 in start_server                                   │
│                                                                                        │
│   170         else:                                                                    │
│ ❱ 171             uvicorn = server.webui(restart=not immediate)                        │
│   172     if args.profile:                                                             │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\webui.py:311 in webui                                           │
│                                                                                        │
│   310     start_common()                                                               │
│ ❱ 311     start_ui()                                                                   │
│   312     modules.sd_models.write_metadata()                                           │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\webui.py:229 in start_ui                                        │
│                                                                                        │
│   228     timer.startup.record("before-ui")                                            │
│ ❱ 229     shared.demo = modules.ui.create_ui(timer.startup)                            │
│   230     timer.startup.record("ui")                                                   │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\modules\ui.py:994 in create_ui                                  │
│                                                                                        │
│    993                                                                                 │
│ ❱  994     loadsave = ui_loadsave.UiLoadsave(cmd_opts.ui_config)                       │
│    995     components = []                                                             │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\w │
│ ebui_nasty_hijacks.py:49 in hijack__init__                                             │
│                                                                                        │
│   48     def hijack__init__(*args, **kwargs):                                          │
│ ❱ 49         Img2imgTabExtender.create_custom_tabs()                                   │
│   50         return original_ui_settings__init__(*args, **kwargs)                      │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\i │
│ mg2img_tab_extender.py:80 in create_custom_tabs                                        │
│                                                                                        │
│    79                 img2img_tabs = cls._get_img2img_tabs()                           │
│ ❱  80                 cls.setup_navigation_events(img2img_tabs)                        │
│    81                 for tab_data in cls.tab_data_list:                               │
│                                                                                        │
│ C:\AI\SDNEXT\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\i │
│ mg2img_tab_extender.py:95 in setup_navigation_events                                   │
│                                                                                        │
│    94         block_data_iterator = zip(img2img_tabs[cls.amount_of_default_tabs:], cls │
│ ❱  95         for tab_block, custom_tab in block_data_iterator:                        │
│    96             def update_func(custom_tab):                                         │
╰───────────────────────────────────────────────────────────────────────────╯
ValueError: zip() argument 2 is longer than argument 1
Appuyez sur une touche pour continuer...

**Comment by John-WL** [comment]
Does this happen when you first start the server, or only on restart?

**Comment by John-WL** [comment]
~~Does this happen when you first start the server, or only on restart?~~ nevermind, in the title. 

I know what the issue is, just don't know why it happens. It's definitely some UI code that shouldn't be running when the backend restarts.
