### ISSUE TITLE
SDNEXT:    AttributeError: 'Options' object has no attribute 'img2img_editor_height'

### ISSUE THREAD

**Issue by RGX650** [John-WL/sd-webui-inpaint-difference#2]
AttributeError: 'Options' object has no attribute 'img2img_editor_height'

15:55:08-422685 ERROR    executing callback:
                         C:\AI\SDNEXT_MASTER\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\webui_callbacks.py
                         after_component_callback: AttributeError
╭─────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────╮
│ C:\AI\SDNEXT_MASTER\automatic\modules\script_callbacks.py:285 in after_component_callback                                                │
│                                                                                                                                          │
│   284 │   │   │   t0 = time.time()                                                                                                       │
│ ❱ 285 │   │   │   c.callback(component, **kwargs)                                                                                        │
│   286 │   │   │   timer(t0, c.script, 'after_component')                                                                                 │
│                                                                                                                                          │
│ C:\AI\SDNEXT_MASTER\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\webui_callbacks.py:35 in on_after_component  │
│                                                                                                                                          │
│   34 │   │   │   DifferenceGlobals.ui_params = ui_params  # for hiding/showing when clicking                                             │
│ ❱ 35 │   │   create_inpaint_difference_ui(                                                                                               │
│   36 │   │   │   BlockManager(tab),                                                                                                      │
│                                                                                                                                          │
│ C:\AI\SDNEXT_MASTER\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\ui.py:17 in create_inpaint_difference_ui     │
│                                                                                                                                          │
│   16 │   │                                                                                                                               │
│ ❱ 17 │   │   DifferenceGlobals.inpaint_mask_component = gr.Image(label="Difference mask", int                                            │
│   18                                                                                                                                     │
│                                                                                                                                          │
│ C:\AI\SDNEXT_MASTER\automatic\modules\shared.py:621 in __getattr__                                                                       │
│                                                                                                                                          │
│   620 │   │   │   return self.data_labels[item].default                                                                                  │
│ ❱ 621 │   │   return super(Options, self).__getattribute__(item) # pylint: disable=super-with-                                           │
│   622                                                                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Options' object has no attribute 'img2img_editor_height'

**Comment by John-WL** [comment]
Ah, I think the `opts.img2img_editor_height` option is missing in SD.Next. I'll try to fix it today or tomorrow.

**Comment by John-WL** [comment]
Should be fixed now with the last commit I did.
