### ISSUE TITLE
AttributeError: 'list' object has no attribute 'is_negative_prompt'

### ISSUE THREAD

**Issue by RGX650** [John-WL/sd-webui-inpaint-difference#5]
19:06:20-656180 ERROR    gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
[2023-11-21 19:06:20,656] sd: [ERROR] gradio call: AttributeError
╭────────────────────────── Traceback (most recent call last) ──────────────────────────╮
│ C:\AI\SDNEXT\automatic\modules\call_queue.py:34 in f                                  │
│                                                                                       │
│   33 │   │   │   try:                                                                 │
│ ❱ 34 │   │   │   │   res = func(*args, **kwargs)                                      │
│   35 │   │   │   │   progress.record_results(id_task, res)                            │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\extensions\sd-webui-inpaint-difference\lib_inpaint_difference\ │
│ webui_nasty_hijacks.py:35 in hijack_func                                              │
│                                                                                       │
│   34 │   │                                                                            │
│ ❱ 35 │   │   return original_img2img_processing(id_task, mode, prompt, negative_promp │
│   36 │   │   │   init_img_with_mask, inpaint_color_sketch, inpaint_color_sketch_orig, │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\modules\img2img.py:226 in img2img                              │
│                                                                                       │
│   225 │   │   if processed is None:                                                   │
│ ❱ 226 │   │   │   processed = processing.process_images(p)                            │
│   227 │   p.close()                                                                   │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\modules\processing.py:738 in process_images                    │
│                                                                                       │
│    737 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):          │
│ ❱  738 │   │   │   │   res = process_images_inner(p)                                  │
│    739 │   finally:                                                                   │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py │
│ :42 in processing_process_images_hijack                                               │
│                                                                                       │
│    41 │   │   │   # we are not in batch mode, fallback to original function           │
│ ❱  42 │   │   │   return getattr(processing, '__controlnet_original_process_images_in │
│    43                                                                                 │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\modules\processing.py:859 in process_images_inner              │
│                                                                                       │
│    858 │   │   │   if shared.backend == shared.Backend.ORIGINAL:                      │
│ ❱  859 │   │   │   │   uc = get_conds_with_caching(modules.prompt_parser.get_learned_ │
│    860 │   │   │   │   c = get_conds_with_caching(modules.prompt_parser.get_multicond │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\modules\processing.py:817 in get_conds_with_caching            │
│                                                                                       │
│    816 │   │   with devices.autocast():                                               │
│ ❱  817 │   │   │   cache[1] = function(shared.sd_model, required_prompts, steps)      │
│    818 │   │   cache[0] = (required_prompts, steps)                                   │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\venv\lib\site-packages\sdwss\hijacker.py:12 in wrapper         │
│                                                                                       │
│   11 │   │   │   def wrapper(*args, **kwargs):                                        │
│ ❱ 12 │   │   │   │   return function(*args, **kwargs, original_function=self.__origin │
│   13                                                                                  │
│                                                                                       │
│ C:\AI\SDNEXT\automatic\venv\lib\site-packages\sdwss\sd_webui\prompt_parser.py:22 in   │
│ get_learned_conditioning                                                              │
│                                                                                       │
│    21 │   hires_steps, use_old_scheduling, *_ = args if args else (None, True)        │
│ ❱  22 │   encoder = PromptScheduleEncoder(model, prompts, steps, hires_steps, not pro │
│    23 │   conds = [encoder.process_prompt(prompt) for prompt in prompts]              │
╰───────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'list' object has no attribute 'is_negative_prompt'

**Comment by John-WL** [comment]
This is an error that was introduced with sdwss. I will have time thuseday to look into it. 

Meanwhile, if you still need to use the extension, you can revert to a previous commit until it's fixed. 
The last commit was code refactoring, so you're not gonna miss on any new feature for now if you rollback.

**Comment by John-WL** [comment]
So the commit to revert to is `d37a705` if you need this extension before thursday.

**Comment by RGX650** [comment]
Ill wait for your magic :) The previous version was messing up my SDNEXT with the hijack. the loaded basemodel was frozen and impossible to unload/reload it or another one without full restart.
Nice work btw !

**Comment by John-WL** [comment]
I removed the sdwss dependency, it should work now.
